### ISSUE TITLE
function to mask the message on the client

### ISSUE THREAD

**Issue by perdugames** [LudiDorici/godot-websocket#1]
I thought it would be nice to have a function to mask the message on the client, since it is a recommendation from [RFC6455](https://tools.ietf.org/html/rfc6455#section-5.3), they actually tell it to write servers so they do not accept messages that are not masked. Or am I reading outdated information and changed?

**Comment by Faless** [comment]
For what I see the library already takes care of masking client to server messages.

See this screenshot of wireshark capturing websocket packets:

![maskedwr](https://user-images.githubusercontent.com/1687918/31818711-98bf9cf0-b599-11e7-8f11-5e0a3d5c203a.png)

![masked2](https://user-images.githubusercontent.com/1687918/31818761-c86ffcd8-b599-11e7-89e1-4d82102e2485.png)

What makes you think it does not mask it as expected from the RFC?

**Comment by perdugames** [comment]
I have to be wrong, I was using a code that masked and the message arrived at the masked server, when I send this module to the server (it's a server external to godot websocket) it's coming clean, and I'm not doing anything to unmask the message on the server side, then I thought maybe I was without a mask.

**Comment by Faless** [comment]
@PerduGames sounds strange, usually you don't have to mask/unmask manually because it's handled by the client/server library.

If the server was not unmasking automatically with your old, non-lws, code, chances are, you were not properly setting the MASK bit in your previous implementation.

**Comment by perdugames** [comment]
is I thought about it, because I'm using the ws module on nodejs on the server, which I believe unmask automatically, the truth is that I'm using a code that is not mine, and I think they're masking it wrong, I'll do an implementation of mine here to learn , but I believe the ws already unmask even though I have not found anything in the documentation about.
