### ISSUE TITLE
Readme change

### ISSUE THREAD

**Issue by AngelOnFira** [LudiDorici/godot-websocket#10]
Not too important, but maybe mention in readme that this has been included in the Godot repo. I spent some time here getting ready to compile it with Godot only to find that it was already there. Not sure if it is included in the current release though.

**Comment by Faless** [comment]
You are totally right, thank you for taking your time to open this issue.

I updated the README clarifying that the module was merged in Godot and that it will be available in official releases starting from Godot 3.1.
