### ISSUE TITLE
Using the demos against Godot 3.1

### ISSUE THREAD

**Issue by crazedVic** [LudiDorici/godot-websocket#12]
With the module now being part of Godot 3.1, are there plans to move the demos to the godot demos project?  If I want to try these demos in 3.1 is there anything I need to change/adjust so that it uses the built-in modules not the ones in this repository?  I just finished building a game using the regular networking and am looking to now support HTML5/websockets, and being able to run / walkthru your demos would be a huge help!

**Comment by Faless** [comment]
Hi @crazedVic , sorry about the delay, I was very busy recently.
The demos were mostly working, but I updated them with few small changes.
They are now fully compatible with the latest 3.1 stable version.

Do you think adding them to the godot demo repo would be useful?
If you had to choose, would you prefer having the multiplayer demo or the websocket chat included?

Thank you for your interest, and sorry again for the delay.

**Comment by Faless** [comment]
Demos are being added to the official demo repository via godotengine/godot-demo-projects#343
