### ISSUE TITLE
Example into official documentation

### ISSUE THREAD

**Issue by greenfox1505** [LudiDorici/godot-websocket#14]
The multiplayer_demo here should be part of this project:
https://github.com/godotengine/godot-demo-projects/tree/master/networking

From my testing using Chrome on Ubuntu18.04, it works perfectly. Unless there is something I'm missing, I believe this demo should be part of the official Godot examples.

**Comment by Faless** [comment]
Thanks, that demo (slightly improved) is being added as `websocket_multiplayer` via godotengine/godot-demo-projects#343
