### ISSUE TITLE
I find that when use Godot WEbsocket Client connect  to WebSocket Server implemented in other languages, sometimes the connection becomes unstable

### ISSUE THREAD

**Issue by colorworlds** [LudiDorici/godot-websocket#17]
I've set up a more detailed description here：
 [gd-websocket-issue](https://gitee.com/colorworlds/gd-websocket-issue/tree/master)

**Comment by Faless** [comment]
As mentioned in the readme, this module was merged in Godot Engine master branch and is available in official Godot Engine releases starting from version 3.1. This repository is no longer mantained and only left for historical purpose. All further development will be done inside the Godot Engine repository.

Please open an issue on the official godot repository (following the issue template) here: https://github.com/godotengine/godot/issues
