### ISSUE TITLE
Error initiating connection in _ready() or _init()

### ISSUE THREAD

**Issue by perdugames** [LudiDorici/godot-websocket#2]
I do not know if this behavior is expected, I'm sorry if it is, but when I try to start a connection in a "_init()" or "_ready()" the connection is established but then it is undone by receiving the error "connection_error ":

```
Connecting to host: myhost : 8080
[2017/10/20 15:45:19:4411] NOTICE: lws_client_connect_2: 0x561d6c889f10: address 102.147.63.77
Client just disconnected
[2017/10/20 15:45:19:7697] NOTICE: lws_context_destroy: ctx 0x561d6c87d040
[2017/10/20 15:45:19:7697] NOTICE: lws_vhost_destroy1
[2017/10/20 15:45:19:7697] NOTICE: lws_context_destroy2: ctx 0x561d6c87d040
[2017/10/20 15:45:19:7698] NOTICE: lws_vhost_destroy2: 0x561d6c889c30
[2017/10/20 15:45:19:7698] NOTICE:   lws_vhost_destroy2: Freeing vhost 0x561d6c889c30

```
it works perfectly when I connect through a button like in the demo game, but when I start with **_init ()** or **_ready ()** I get the error, do I have to give the connection time to set?  or is there really something wrong going on?

edit: I tested it with a timer, specifically below _0.1_ which starts to return me the error.

**Comment by Faless** [comment]
Are you starting the server in the _init / _ready function too. In that case the server might not yet be available when the client tries to connect.

> edit: I tested it with a timer, specifically below 0.1 which starts to return me the error.

Sorry, do you mean it works with the timer or not?

**Comment by perdugames** [comment]
is an external server, it is already connected. Yes, with timer works, if it is above 0.1, if it is 0.1 or below already I get the error.

**Comment by Faless** [comment]
I can't seem to reproduce this issue. It seems an error in your code.
You can see it's working in this simple demo. 
[gd-lws-init.tar.gz](https://github.com/LudiDorici/godot-lws/files/1403359/gd-lws-init.tar.gz)

**Comment by perdugames** [comment]
strange, I tested it here and it's working on localhost too, I realized it's something with the external server, it might be on handshake, too short timeout, I have no idea, anyway the best thing to do is use a timer to connect to the external server, 1 second more or less does not hurt. XD

edit: actually it hurts yes XD
because it can not establish a connection, every time it ends up disconnecting at a time, also messages sent with only **_peer.send(msg)** do not arrive well on the server, only if I do as you did in the project that sent me **_client.get_peer().put_data(msg.to_utf8())** so it arrives correctly, I believe it is because" send "is not converted to **utf8**. But I will not try anymore, if I do not end up bothering, I'll go back to my _ws.gd_ and drop my laziness and finish implementing it there.

**Comment by Faless** [comment]
> also messages sent with only _peer.send(msg) do not arrive well on the server

There is no `send` function in peer, I really can't understand your problem.

Anyway, this issue does not affect the demo provided, so unless you or someone else provide a project affected by the bug I'm closing this as a non issue

**Comment by perdugames** [comment]
but in the example it looks like **_peer.send()**

```
func _on_SendBtn_pressed():
	if _peer == null:
		return
	var txt = get_node("../Panel/VBoxContainer/Send/LineEdit").get_text()
	if txt != "":
		_peer.send(txt) # here
		get_node("../Panel/VBoxContainer/Send/LineEdit").set_text("")
		Utils._log(_log_dest, "Sending data: %s" % txt)
```
I'll see if I make an empty project later here and create an account on some free server to reproduce the effect. Because it could not be an error in the server code, it's working with the gdscript implementation, so I have no idea whatsoever.

**Comment by Faless** [comment]
> but in the example it looks like _peer.send()

I see, you mean the helper class in `utils.gd` in the demo.

Well, if you want to use `put_data` instead of `put_packet` just set `const PACKET = false`

**Comment by perdugames** [comment]
is not this, I am saying that the message arrives on the server with unexpected characters, because it is not converted to utf8, try sending a json you will get some anomalies in the message, then it makes no difference the mode(**_peer.send(msg)** or **_client.get_peer().put_data(msg.to_utf8())**), the important is to convert to utf8, otherwise it will receive unexpected characters on the server side.

About the error of disconnecting, i was connecting to a different port, which for some reason was not working, I switched the server to 80, and I connected to the 80 on the client and it worked in "_ready()" without disconnecting more.

**Comment by Faless** [comment]
> the important is to convert to utf8, otherwise it will receive unexpected characters on the server side.

Sorry, I didn't understand you before. You are right.

That's just how `put_packet` and `var2bytes` work, they encode the data in "Godot format", if you want to only send the string data you have to call `get_peer().put_data(msg.to_utf8())` as you pointed out.
Check out the [docs about serialization](http://docs.godotengine.org/en/stable/learning/features/misc/binary_serialization_api.html) to know more

> About the error of disconnecting, i was connecting to a different port, which for some reason was not working, I switched the server to 80, and I connected to the 80 on the client and it worked in "_ready()" without disconnecting more .

Good to know that it was something in your code and not in the module.
