### ISSUE TITLE
Data does not always get picked up?

### ISSUE THREAD

**Issue by stubbsy345** [LudiDorici/godot-websocket#3]
For some reason the websocket is not picking up that there is a packet to be collected. I have tested my server with numerous practice clients and works fine. I am able to send the data from the websocket, to a server written in ASP.NET. However, data is never received? What could be stopping it from coming through.

**Comment by Faless** [comment]
As a blind guess I'll ask, are you correctly calling `poll` in process or fixed process? Are you receiving the `data_received` signal?

Please provide a project with your issue showing the bug, the demo project provided in the repo works just fine, with both local and remote server.

EDIT:
Are you getting errors in the logs? Can you post the log?

**Comment by stubbsy345** [comment]
Sorry I meant to post this in your demo, not module. It's our fault we have discovered. We are sending a message to our server. We then want to adapt that message and send it back, rather than just echoing it. However, we are having a lot of trouble re-encoding that message in a way the the receiver in godot can pick up. I tried appending 4, 0, 0, 0, x, x, x, x to the beginning like appears to be sent, where the x's adapt depending on the size of the the message, we got something but not what we wanted and we started to receive one and a half messages at times. It was all very confusing and I don't know where we went wrong. It works fine as a direct echo from our server though. SO there is some issue in how we encoded the data back. If you have any examples of this it would be really useful. 

For now, we are continuing with the game and waiting for HTTP client to be available for web exports. We had a thought yesterday though, do you know if there is a way to use the .eval function of the javascript singleton to send a HTTP request and returning the value? I know this can be used to return strings and ints, etc. 

EDIT:
I also added an extra 4 bytes onto the start of the array before sending which seem the be present when received by our server, the value of which appears to be related to the length of the message. This is what allowed us to receive some input back, but it wasn't accurate and often caused crashing of the godot export.

**Comment by Faless** [comment]
I see, well, to avoid having to deal with godot format you can use json to communicate and sending data via `tcp.put_data(JSONSTRING.to_utf8())` (which will send the raw utf8 bytes).

If you want to know more about godot serialization [here is the reference](http://docs.godotengine.org/en/stable/learning/features/misc/binary_serialization_api.html)

**Comment by stubbsy345** [comment]
Ah okay, the sending isn't the issue, it's the receiving, can you give me some advice on how to format a string to be sent back. Say, for example, I want to return "This is your data" as a string. It's easy for me to get the raw utf8 bytes from that, but how should the byte array be built so that godot will accept the packet and read it appropriately. I'm guessing if I return a json I will still have to deal with some godot serialization. If I don't appeand anything to the beginning of the array and just send raw bytes, my godot game doesn't even register that there is a packet. I have read the godot serialization, but there aren't any examples so it's a little difficult to understand.

**Comment by Faless** [comment]
If strings is what you are interested in just send the raw strings from the server and receive them in Godot using `tcp.get_data(tcp.get_available_bytes())[1].get_string_from_utf8()` [see `get_data` docs here](http://docs.godotengine.org/en/latest/classes/class_streampeer.html?highlight=get_data#class-streampeer-get-data)

**Comment by stubbsy345** [comment]
Ah okay thanks, so I don't need the packet peer in this case?

EDIT: Oh amazing got it working. I was using a lot of your example code and hadn't realised I could just use TCP instead of the packet peer to send a string. Can I ask, I want to send long JSONs using this, but using this technique I am getting them in sections. How can I use this to bring these individual strings together to build the JSON. But ensure that they don't combine with other files?
