### ISSUE TITLE
Receiving more than one message as if it were just one

### ISSUE THREAD

**Issue by perdugames** [LudiDorici/godot-websocket#4]
I'm getting stuck messages at times, which leads me to get an invalid JSON error, which is expected, because it has two JSON objects stuck together, for example:
```
message: {"newPos":{"pos":"1:1"}}{"newPos":{"pos":"2:2"}}
```
notice that they are together, two messages have been sent, and he is only returning me one with the contents of the two, the expected was thus:

```
message: {"newPos":{"pos":"1:1"}}
message: {"newPos":{"pos":"2:2"}}
```

which logically leads me to receive _**"SyntaxError: Unexpected token { in JSON at position 59"**_ on the server.

which makes me believe that it is on the client side, that somehow it is sending two messages as if it were just one.

I wanted to have actually checked the data before I came here to make sure it's on the client or not that this is happening, but I'm not sure how to check the message before. The only thing I'm checking is here:
```
func send(msg):
	_log("Sending data: %s" % msg)
	_client.get_peer().put_data(msg.to_utf8())
```
and I'm getting it right, but is there anything else to check after that might be the problem on the client?

**Edit:** I did the test on a simplistic project here (the one you sent me once), and the problem seems to be even on the client. Follow the project file.

[gd-lws-init.zip](https://github.com/LudiDorici/godot-lws/files/1447014/gd-lws-init.zip)

Notice that there is another script embedded in the "RichTextLabel" node to simulate what is happening.

What I believe it is, is that two sends are being called at the same time. This causes the error. Testing on an external server, which is slower than localhost, nor do I need the "RichTextLabel" script to get the error, it simply kills the messages and joins two in one, even with just a "send" in a script . I do not know if this should happen or not, if so, then the right thing would be to make a queue of messages to be sent, so that this does not happen, is it right?

**Comment by Faless** [comment]
I can confirm this problem, we need to properly handle framing with LWS. As of now WS are treated like streams.

**Comment by perdugames** [comment]
but they were no longer treated as "streams"?

**Comment by Faless** [comment]
> but they were no longer treated as "streams"?

they are, and you want to deal with them to send packets, or, more accurately, frames (as per WS RFC).
You can still try to use PacketPeerStream in the meantime, as I probably won't have much time to solve this in the near future.

**Comment by perdugames** [comment]
Use as is being done here? https://github.com/LudiDorici/godot-lws/blob/master/lws_demo/utils.gd

**Comment by Faless** [comment]
> Use as is being done here? https://github.com/LudiDorici/godot-lws/blob/master/lws_demo/utils.gd

More or less, but don't expect that to "just work".
It encodes data in a custom way that won't work out of the box when either the client or server is not a Godot instance (like, in your case, nodejs ws library).

**Comment by perdugames** [comment]
yes, I would not use "var2bytes", am I using JSON, or are you talking about encoding the bytes sent in addition?

**Comment by Faless** [comment]
The code was ported to implement `PakcetPeer` instead of `StreamPeer`, it should now behave correctly.
The GDScript part has been updated, be sure to check it out.
